# Generated by Django 3.1.8 on 2021-06-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superhero',
            name='primary_ability',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='superhero',
            name='secondary_ability',
            field=models.CharField(max_length=100),
        ),
    ]
